// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ81qqH-vCXldPoCpGqxBLTHU7aoP1DyI',
    appId: '1:865558148469:web:85e36f46b8ad1b8e474f3c',
    messagingSenderId: '865558148469',
    projectId: 'hilgo-cargo-project-e0dbc',
    authDomain: 'hilgo-cargo-project-e0dbc.firebaseapp.com',
    storageBucket: 'hilgo-cargo-project-e0dbc.firebasestorage.app',
    measurementId: 'G-76PRD3R488',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9NOBg1ZATkWoZN87GIvBK9QaYAPq_VJ4',
    appId: '1:865558148469:android:4332d12b2be5b1ee474f3c',
    messagingSenderId: '865558148469',
    projectId: 'hilgo-cargo-project-e0dbc',
    storageBucket: 'hilgo-cargo-project-e0dbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQiZfrrBRGkzEde2Xfmhr5UEsfhYpbR0A',
    appId: '1:865558148469:ios:fc4dda11959545a8474f3c',
    messagingSenderId: '865558148469',
    projectId: 'hilgo-cargo-project-e0dbc',
    storageBucket: 'hilgo-cargo-project-e0dbc.firebasestorage.app',
    iosClientId: '865558148469-v48ghp18ivq29a7fc42efdq03dt626s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQiZfrrBRGkzEde2Xfmhr5UEsfhYpbR0A',
    appId: '1:865558148469:ios:fc4dda11959545a8474f3c',
    messagingSenderId: '865558148469',
    projectId: 'hilgo-cargo-project-e0dbc',
    storageBucket: 'hilgo-cargo-project-e0dbc.firebasestorage.app',
    iosClientId: '865558148469-v48ghp18ivq29a7fc42efdq03dt626s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ81qqH-vCXldPoCpGqxBLTHU7aoP1DyI',
    appId: '1:865558148469:web:a09aefc3ada1d259474f3c',
    messagingSenderId: '865558148469',
    projectId: 'hilgo-cargo-project-e0dbc',
    authDomain: 'hilgo-cargo-project-e0dbc.firebaseapp.com',
    storageBucket: 'hilgo-cargo-project-e0dbc.firebasestorage.app',
    measurementId: 'G-FDE0BZXN4F',
  );

}